version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    ports:
      - 5432:5432